// Generates src/index.ts — the lucide-style barrel — from @mdi/svg (the canonical MDI SVG set).
// Each icon becomes one PURE-annotated named export sharing the createIcon factory, so bundlers
// tree-shake everything you don't import. Re-run whenever @mdi/svg updates (see the GitHub Action).
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const svgDir = join(root, "node_modules/@mdi/svg/svg");

const pascal = (file) =>
  file
    .replace(/\.svg$/, "")
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");

const files = readdirSync(svgDir).filter((f) => f.endsWith(".svg")).sort();
const seen = new Set();
const lines = [
  '// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.',
  'import { createIcon } from "./createIcon";',
  '',
  'export { createIcon } from "./createIcon";',
  'export type { Icon, IconProps } from "./createIcon";',
  '',
];

let count = 0;
for (const file of files) {
  const svg = readFileSync(join(svgDir, file), "utf8");
  const d = svg.match(/\sd="([^"]+)"/)?.[1];
  if (!d) continue;
  let name = pascal(file);
  if (/^[0-9]/.test(name)) name = "Mdi" + name; // valid JS identifier (some MDI names start with a digit)
  if (seen.has(name)) continue;
  seen.add(name);
  lines.push(`export const ${name} = /*#__PURE__*/ createIcon(${JSON.stringify(d)});`);
  count++;
}

writeFileSync(join(root, "src/index.ts"), lines.join("\n") + "\n");
console.log(`Generated ${count} icons → src/index.ts`);
